/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.code.codebuilderapp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

// made following instructions here: https://spring.io/guides/gs/messaging-stomp-websocket/
// and here: https://www.mokkapps.de/blog/sending-message-to-specific-anonymous-user-on-spring-websocket/
// and using this discussion on principal https://stackoverflow.com/questions/37853727/where-user-comes-from-in-convertandsendtouser-works-in-sockjsspring-websocket
@SpringBootApplication
public class CodeBuilderApplication {
    public static void main(String[] args) {
        SpringApplication.run(CodeBuilderApplication.class, args);
    }
}

/* Sample test code
public class Foo {
  public static void main(String[] args) {
    System.out.println("Hello world!");
  }
}
*/
