/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.code.codebuilderapp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

// made following instructions here: https://spring.io/guides/gs/messaging-stomp-websocket/
@SpringBootApplication
public class CodeBuilderApplication {
    public static void main(String[] args) {
        SpringApplication.run(CodeBuilderApplication.class, args);
    }
}
