package org.code.playground;

public enum PlaygroundSignalKey {
  ADD_ITEM,
  ADD_CLICKABLE_ITEM,
  CHANGED_ITEM,
  RUN,
  PLAY_SOUND,
  REMOVE_ITEM,
  REMOVE_CLICKABLE_ITEM,
  FINISHED_CLICK_EVENT,
  STARTED_CLICK_EVENT,
  SET_BACKGROUND_IMAGE
}
